# Whenever a push is made to the master branch then run the job
on:
  push:
    branches:
      - master

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1
    - name: export
      uses: firebelley/godot-export@v2.4.0
      with:
        base_version: 0.1.0
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_export_templates.tpz
        #godot_template_version: 3.2.2
        relative_project_path: ./
      env:
        GITHUB_TOKEN: ${{ secrets.EXPORT_GITHUB_TOKEN }}
