on:
  release:
    types: [created, edited]
jobs:
#   release_windows:
#     runs-on: ubuntu-latest
#     steps:
#       - name: download widows
#         uses: dsaltares/fetch-gh-release-asset@master
#         with:
#           file: color-maze-win.zip
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#       - name: release windows
#         uses: josephbmanley/butler-publish-itchio-action@master
#         env:
#           BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
#           CHANNEL: win
#           ITCH_GAME: color-maze
#           ITCH_USER: flber
#           PACKAGE: color-maze-win.zip
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: color-maze-linux.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: release linux
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: color-maze
          ITCH_USER: flber
          PACKAGE: color-maze-linux.zip  
  release_osx:
    runs-on: ubuntu-latest
    steps:
      - name: download osx
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: color-maze-osx.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: release osx
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: color-maze
          ITCH_USER: flber
          PACKAGE: color-maze-osx.zip
  release_html5:
    runs-on: ubuntu-latest
    steps:
      - name: download html5
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: color-maze-html5.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: release html5
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: color-maze
          ITCH_USER: flber
          PACKAGE: color-maze-html5.zip  
